version: '3.7'

services:
    react:
        build:
            context: .
        networks:
            - frontend

    proxy:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "3000:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            - frontend
            
networks:
    frontend:
        driver: bridge